export const FETCH_USER = "FETH_USER";
export const CREATE_PACKAGE = "CREATE_PACKAGE";
export const OPEN_BOTTOM_DRAWER = "OPEN_BOTTOM_DRAWER";
export const CLOSE_BOTTOM_DRAWER = "CLOSE_BOTTOM_DRAWER";
